environment:
  matrix:
    - APPVEYOR_BUILD_SYSTEM: Visual Studio 2019
    - APPVEYOR_BUILD_SYSTEM: mingw

install:
  - if %APPVEYOR_BUILD_SYSTEM% == Visual Studio 2019 (
      choco install visualstudio2019buildtools --package-parameters "--includeRecommended" -y
    )
  - if %APPVEYOR_BUILD_SYSTEM% == mingw (
      choco install mingw -y
    )
  - set CURL_DIR=C:\tools\mingw64
  - set PATH=%CURL_DIR%\bin;%PATH%
  - cmake --version

build_script:
  - mkdir build
  - cd build
  - cmake ..
  - cmake --build .

test_script:
  - ctest -C Debug --output-on-failure
